# Generated by Django 6.0 on 2025-12-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assignment_assignmentsubmission_coursecomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Any communication info or reason for joining'),
        ),
    ]
