# Generated by Django 6.0 on 2025-12-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollmentrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Any additional note for the instructor'),
        ),
    ]
